version: "3.7"
services:
  app:
    build: .
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://mongodb:27017/transportationdb
    container_name: bus-api
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - mongodb
    links:
      - mongodb
    networks:
      - app-tier
    deploy:
      resources:
        limits:
          memory: 3000M
  mongodb:
    image: mongo
    container_name: mongodb
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGODB_APPLICATION_DATABASE: transportationdb
    networks:
      - app-tier
    command: mongod --logpath=/dev/null # --quiet
networks:
  app-tier:
    driver: bridge